coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default

ignore:
  - "build/**/*" # Build configs
  - "cmd/**/*" # Commands
  - "third_party/**/*" # Ent generated files shouldn't be tracked
  - "test/**/*" # Test utilities