// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"github.com/arpb2/C-3PO/pkg/ent/credential"
	"github.com/arpb2/C-3PO/pkg/ent/user"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// CredentialCreate is the builder for creating a Credential entity.
type CredentialCreate struct {
	config
	salt          *[]byte
	password_hash *[]byte
	holder        map[uint]struct{}
}

// SetSalt sets the salt field.
func (cc *CredentialCreate) SetSalt(b []byte) *CredentialCreate {
	cc.salt = &b
	return cc
}

// SetPasswordHash sets the password_hash field.
func (cc *CredentialCreate) SetPasswordHash(b []byte) *CredentialCreate {
	cc.password_hash = &b
	return cc
}

// SetHolderID sets the holder edge to User by id.
func (cc *CredentialCreate) SetHolderID(id uint) *CredentialCreate {
	if cc.holder == nil {
		cc.holder = make(map[uint]struct{})
	}
	cc.holder[id] = struct{}{}
	return cc
}

// SetHolder sets the holder edge to User.
func (cc *CredentialCreate) SetHolder(u *User) *CredentialCreate {
	return cc.SetHolderID(u.ID)
}

// Save creates the Credential in the database.
func (cc *CredentialCreate) Save(ctx context.Context) (*Credential, error) {
	if cc.salt == nil {
		return nil, errors.New("ent: missing required field \"salt\"")
	}
	if cc.password_hash == nil {
		return nil, errors.New("ent: missing required field \"password_hash\"")
	}
	if len(cc.holder) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"holder\"")
	}
	if cc.holder == nil {
		return nil, errors.New("ent: missing required edge \"holder\"")
	}
	return cc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CredentialCreate) SaveX(ctx context.Context) *Credential {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cc *CredentialCreate) sqlSave(ctx context.Context) (*Credential, error) {
	var (
		c     = &Credential{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: credential.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: credential.FieldID,
			},
		}
	)
	if value := cc.salt; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  *value,
			Column: credential.FieldSalt,
		})
		c.Salt = *value
	}
	if value := cc.password_hash; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  *value,
			Column: credential.FieldPasswordHash,
		})
		c.PasswordHash = *value
	}
	if nodes := cc.holder; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   credential.HolderTable,
			Columns: []string{credential.HolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint,
					Column: user.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	c.ID = int(id)
	return c, nil
}
