name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: ./hack/install-go-dependencies.sh

    - name: Install goimports
      run: ./hack/install-go-imports.sh

    - name: Run docker image
      run: ./hack/verify-go-docker.sh

    - name: Run fmt
      run: ./hack/verify-go-fmt.sh

    - name: Run goimports
      run: ./hack/verify-go-imports.sh

    - name: Run package imports
      run: ./hack/verify-go-package-imports.sh

    - name: Run govet
      run: ./hack/verify-go-vet.sh

    - name: Run build
      run: ./hack/verify-go-build.sh

    - name: Run unit tests
      run: ./hack/verify-go-unit-test.sh

    - name: Run integration test
      run: ./hack/verify-go-integration-test.sh

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        yml: ./.codecov.yml